#!/bin/sh

# Using cairo graphics svg2png:
#     http://cairographics.org/
#     http://cairographics.org/snapshots/svg2png-0.1.3.tar.gz

alias inkscape="/Applications/Inkscape.app/Contents/Resources/script"


width=${1:-'20'}
files=${@:2}

if [[ -z "$files" ]]; then
    files=$(ls *.svg)
fi

for f in $files; do
    dir="$(dirname $f)/png/${width}x"
    [[ -d $dir ]] || mkdir -p $dir
    outfile=$dir/$(basename $f '.svg').png
    svg2png -w $width $f $outfile

    # inkscape --export-png="$PWD/$outfile" --export-width=$width "$PWD/$f"

    pngout $outfile
done
